"""rename department

Revision ID: 3ae8f23d030c
Revises: 72a885e62669
Create Date: 2024-07-01 16:21:35.205433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae8f23d030c'
down_revision = '72a885e62669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')

    # ### end Alembic commands ###
